INSERT INTO CARTE (codCarta, nome, tipo, descrizione, costoMana, attributo, attacco, difesa, effetto) VALUES (0, "Mostro delle paludi","bestia","Mostro",null,"Acqua",1500,1000,"Quando evocato guadagna 500 ATK"),
(1, "Drago bianco occhi blu","drago","Mostro",null,"Luce",3000,2500,"Una volta per turno distruggi un Mostro"),
(2, "Signore del fuoco","guerriero","Mostro",null,"Fuoco",2200,2000,"Una volta per turno raddoppia l'attacco di questa carta"),
(4, "Jinzo","macchina","Mostro",null,"Oscurità",2500,1000,"Le carte trappola non possono essere attivate"),
(5, "Levia-dragon deadelus","leviatano","Mostro",null,"Acqua",3500,3500,"Quando evocato distruggi tutte le altre carte sul terreno"),
(6, "Strike ninja","guerriero","Mostro",null,"Oscurità",1500,2000,"Quando evocato guadagna 500 DEF"),
(7, "Takuhee","Mostro volante","Mostro",null,"Vento",1800,1050,"Una volta per turno cambia la posizione di un Mostro"),
(8, "Garuda the wind spirit","Mostro volante","Mostro",null,"Vento",1500,1000,"Quando evocato guadagna 1000 ATK"),
(9, "Cyber dragon","Macchina","Mostro",null,"Luce",2100,1000,"Se non controlli mostri evoca specialmente questa carta dalla tua mano"),
(10, "GreatFly","Insetto","Mostro",null,"Terra",1500,3000,"Quando evocato guadagna 500 ATK"),
(11, "Giara dell'avidità","normale","Magia",500,null,null,null,"Pesca due carte"),
(12, "Lancia del destino","rapida","Magia",200,null,null,null,"Riduci l'attacco e difesa di un Mostro a 0"),
(13, "Scudo di pietra","rapida","Magia",100,null,null,null,"Un Mostro guadagna 1000 DEF fino alla fine del turno"),
(14, "Excalibur","equipaggiamento","Magia",100,null,null,null,"Un Mostro guadagna 1000 ATK"),
(15, "Siero paralizzante","continua","Magia",100,null,null,null,"Tutti i mostri del tuo avversario perdono 500 ATK"),
(16, "Mostro resuscitato","normale","Magia",500,null,null,null,"Evoca specialmente un Mostro dal tuo cimitero"),
(17, "Tifone spaziale mistico","rapida","Magia",300,null,null,null,"Distruggi una carta Magia/trappola sul terreno"),
(18, "Messagero di pace","continua","Magia",1000,null,null,null,"I mostri con più di 2000 ATK non possono attaccare"),
(19, "Spada e scudo","normale","Magia",300,null,null,null,"Scambia l'ATK e la DEF di tutti i mostri sul terreno"),
(20, "Ricca miniera","terreno","Magia",1000,null,null,null,"Una volta per turno il giocatore può pagare 1000 LP per pescare una carta"),
(21, "Giara della ricchezza","normale","Trappola",1000,null,null,null,"Pesca 5 carte"),
(22, "Forza riflessa","normale","Trappola",1000,null,null,null,"Distruggi tutti i mostri del tuo avversario"),
(23, "Giudizio solenne","Contro Trappola","Trappola",1000,null,null,null,"Quando il tuo avversario attiva l'effetto di una carta, negane e distruggila"),
(24, "Virus pandemico eradicatore","normale","Trappola",1000,null,null,null,"Distruggi tutti i mostri con più di 1500 ATK nel terreno e mano del tuo avversario"),
(25, "Imperial order","continua","Trappola",1000,null,null,null,"Le carte Magia non possono essere attivate"),
(26, "Destruction potion","normale","Trappola",500,null,null,null,"Distruggi un Mostro e guadagna LP pari al suo ATK"),
(27, "Time seal","normale","Trappola",1000,null,null,null,"Salta la prossima fase di pesca del tuo avversario"),
(28, "Avalon","Trappola","Trappola",500,null,null,null,"Quando un tuo Mostro viene distrutto pesca una carta"),
(29, "Cerchio incantatore","continua","Trappola",100,null,null,null,"Un Mostro del tuo avversario non può attaccare"),
(30, "Energia cresente","normale","Trappola",500,null,null,null,"Raddoppia l'attacco di un tuo Mostro");